<style>
   
</style>

<?php
$properties = $this->properties;
$perpage = Zend_Registry::get('perpage');
$section = $this->section;
$link = $this->link;
?>
<link href="<?php echo NHK_URL::getLinkPublic("css") ?>/list.css" media="screen" rel="stylesheet" type="text/css" />
<!--header-->
<div class="page-header">
    <div class="title">
        <h1>KIỂM TRA SỐ LƯỢNG USER ĐANG ONLINE</h1>
    </div>
    
    <div class="row"></div>
</div>
<!--/header-->

<!--search-->


<!--/search-->




<!--table list-->
<!--<div style="display:none;" id="content">-->
<div id="contentss" style="position: relative;">
    <style type="text/css">
        table .cCheckBox{width: 35px; padding: 2px;}
        table .cOrder{width: 35px; padding: 2px;}
        table .c1{width: 130px; padding: 2px;}
        table .c2{width: 200px; padding: 2px;}
        table .c3{ padding: 2px;}
        table .c4{width: 100px; padding: 2px;}
        table .c55{width: 200px; padding: 2px;}
        table .c5{width: 150px; padding: 2px;}
        table .c6{width: 100px; padding: 2px;}

        table .cFunc{width: 100px; padding: 2px;}

    </style>
    <div id="table-header" style="overflow: hidden;">
        <table class="table table-striped table-bordered table-header" style="width:1250px;">       
            <thead>
                <tr>
                    
                    <th class="cOrder"><?php echo NHK_Properties::get("title_column_order", 'public', $properties); ?></th>
                    <th class="c1">Username</th>
                    <th class="c2">IP đăng nhập</th>
                    <th class="c3">Thời gian đăng nhập</th>

                    <th class="cFunc"><?php echo NHK_Properties::get("title_column_function", 'public', $properties); ?></th>
                </tr>
            </thead>
        </table>

    </div>

    <div id="table-data" style="overflow: auto;">
        <table  class="table table-striped table-hover table-condensed table-bordered" style="width:1250px;">
            <tbody id="data_table">
                <?php $stt=0; foreach ($this->data as $item) { ?>
                    <tr>
                        <td class="cOrder" style="text-align:center;"><?php echo $stt + 1; ?></td>
                        <td class="c1"><?=$item->username?></td>
                        <td class="c2"><?=$item->ip?></td>
                        <td class="c3"><?=date("d-m-Y H:i:s",$item->time)?></td>
                        <td class="cFunc" style="text-align:center;">
                            <div class="btn-group">                            
                              <a title="Xóa"  class="btn btn-small btn-danger group_btn_delete" href="<?=NHK_URL::getLinkControllerAdmin('user')?>/delete-online/id/<?=$item->id?>/username/<?=$item->username?>"> <i class="icon-trash icon-white"></i></a>
                            </div>
                          </td>
                    </tr>
                <?php }?>
                    
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">
    var url = '<?php echo NHK_URL::getLinkControllerAdmin($link); ?>';
/
    $(document).ready(function () {


        /*---- table-----*/

        $("#table-data").scroll(function () {
            var scrollLeft = $(this).scrollLeft();
            $("#table-header").scrollTo(scrollLeft);
        });

        initTable();
        /*---- end table-----*/

    });

    

    initTable = function () {

        if ($(".table-header").width() > $(window).width()) {
            var w = $(".table-header").find('th:last').width();
            $(".table-header").width($(".table-header").width() + 17);
            $(".table-header").find('th:last').width(parseInt(w) + 17);
        }


    };


</script>
<script src="<?php echo NHK_URL::getLinkPublic("js") ?>/jquery_scrollTo.js" type="text/javascript"></script>
<script src="<?php echo NHK_URL::getLinkPublic("js") ?>/list.js" type="text/javascript"></script>
