<style>
    .thaydoiweblaygia li{
        margin-top: 15px;
    }
    .thaydoiweblaygia-info{
        color: #F00;
        font-weight: bold;
    }
  </style>

<?php
$properties = $this->properties;
$perpage = Zend_Registry::get('perpage');
$section = $this->section;
$link = $this->link;
?>
<link href="<?php echo NHK_URL::getLinkPublic("css") ?>/list.css" media="screen" rel="stylesheet" type="text/css" />
<!--header-->
<div class="page-header">
  <div class="title">
      <h1>Thay đổi trang web lấy giá</h1>
  </div>
  
  <div class="row"></div>
</div>
<!--/header-->

<form id="myForm" method="post" action="<?php echo NHK_URL::getLinkControllerAdmin($this->link) ?>/thaydoiwebsitelaygia">

    
    <ul class="thaydoiweblaygia">
        <li><input <?php if($this->config['config_val']==1 ) echo "checked"; ?> type="radio" name="web" value="1" /> Web taiem.com</li>
        <li><input <?php if($this->config['config_val']==2 ) echo "checked"; ?> type="radio" name="web" value="2" /> Web ngoaite.phuthinh.com.vn</li>
        <li><input <?php if($this->config['config_val']==0 ) echo "checked"; ?> type="radio" name="web" value="0" /> Không hiển thị Giá Ngoại Tệ</li>
        <li><button>Cập nhật</button></li>
    </ul>
    
   
        
        
</form>

<div class="thaydoiweblaygia-info">
    <?php
        if(isset($this->info))
            echo $this->info;
    ?>
</div>






