<div class="box-main">
  <?php if($this->data): ?>
  <?php $data = $this->data; ?>
    <style>
        .detail-news h2{
            color: #FFFF00;
        }
        .detail-news{
            color: #eee;
        }
    </style>
    
    <div class="box-main-header">
       <h1 class="box-main-header-title">
           <span class="box-main-header-title-icon">TIN TỨC > &nbsp;
  <?= $data->title ?>
            </span>
            </h1>
  
  </div>
    <div style="padding: 10px;" class="box-main-content detail-news">
    <h2>
        <?= $data->title ?>
    </h2>
    <div style="font-style: italic;">
         <?php if($data->time_post != ''): 
                      echo $data->time_post;
                    else:
                      echo date("d-m-Y H:i:s",strtotime($data->created_at)); 
                    endif;
                      ?>
    </div>
    <div style="margin-left: 10px; margin-top: 20px; margin-bottom: 10px; font-weight: bold;">
        <?php if($data->page == 'vietstock.vn'): ?>
          <?= $data->short_des ?>
      
          <?php endif; ?>
    </div>
    <div style="text-align: left;">
        <?php if($data->page != 'vietstock.vn'): ?>
        <img src="<?= $data->thumb_img ?>" title="<?= $data->title ?>" alt="<?= $data->title ?>" width="100px" />
        <?php endif; ?>
        <?= $data->short_des?>
    </div>
      <br />
      <hr />
    <div style="margin-left: 10px; padding: 10px;">
        <?= $data->description ?>
      </div>
  </div>
  <?php endif; ?>
</div>
