<style>
    .index-news{
        
    }
    .index-news p{
        color: #FFF;
    }
</style>
<div class="box-main">
  <div class="box-main-header">
       <h1 class="box-main-header-title">
            <span class="box-main-header-title-icon">DANH SÁCH TIN TỨC</span>
            </h1>
  </div>
  <div style="padding: 10px;" class="box-main-content index-news">
    <?php foreach ($this->data as $item): ?>
      <?php $new_url = NHK_URL::getLinkControllerDefault('news').'/detail/id/'.$item['id']; ?>
      <div class="media">
        <a class="pull-left" title="<?= $item['title'] ?>" href="<?= $new_url ?>">
          <img width="100" height="100" src="<?= $item['thumb_img'] ?>" class="media-object" data-src="holder.js/100x100">
          <p style="font-style: italic; color: #ddd; font-size: 12px;">
              <?php if($item['time_post'] != ''): 
                      echo $item['time_post'];
                    else:
                      echo date("d-m-Y H:i:s",strtotime($item['created_at'])); 
                    endif;
                      ?>
          </p>
        </a>
        <div class="media-body">
          <a title="<?= $item['title'] ?>" href="<?= $new_url ?>" >
            <h4 class="media-heading"><?= $item['title'] ?>
            <?php if(date("Y-m-d") == date("Y-m-d",strtotime($item['created_at']))): ?>
            <img src="<?= NHK_URL::getLink('img') ?>/new_small.gif" />
              <?php endif; ?>
            </h4>
          
           
          </a>
          <p>
            <?= $item['short_des'] ?>
          </p>
          
        </div>
      </div>
    <?php endforeach; ?>
  </div>
</div>

<div>
  <?php //echo $this->paginationControl($this->paginator, 'Sliding', 'news/pagination.phtml'); ?>
</div>



<script src="<?php echo NHK_URL::getLinkPublic("js") ?>/holder.js" type="text/javascript"></script>
