 <div class="span4">
      <h3>Biểu đồ giá vàng 24h - live</h3>
      <div class="post_center">
<!--        <img width="180" height="114" alt="24 hr gold chart" src="http://www.kitco.com/images/live/t24_au_en_usoz_home.gif?random=<?=date("YmdHi")?>">-->
      </div>
    </div>
    <div class="span4">
      <h3>BIỂU ĐỒ USD INDEX</h3>
      <div class="post_center">
<!--        <img width="180" height="114" alt="24 hr gold chart" src="http://www.weblinks247.com/indexes/idx24_usd_en_2.gif?random=<?=date("YmdH")?>">-->
      </div>
   </div>
    <div class="span4">
      <h3>Ngoại tệ quốc tế</h3>
      <div>
<!--        <iframe width="216" height="230" scrolling="no"  frameborder="0" src="http://classic.easy-forex.com/en/forex.quotesbox.aspx" name="Forex"></iframe>-->
      </div>
    </div>