<div class="box-header">GIÁ VÀNG TẠI CÔNG TY SJC CẦN THƠ</div>
<div class="box-content">
  <ul class="nav nav-tabs" id="myTab_SJC_CanTho" style="margin-bottom: 0px;">
    <li class="active"><a data-toggle="tab" href="#cantho">Bảng giá trực tuyến tại Cần Thơ</a></li>
    <li><a data-toggle="tab" href="#angiang">Bảng giá trực tuyến tại An Giang</a></li>
  </ul>

  <div class="tab-content">
    <div class="tab-pane active" id="cantho">
      <h3>Cần Thơ</h3>
      <div class="cantho" id="content_cantho">
                <iframe width="100%" scrolling="yes" height="250" frameborder="0" style="border:0px; overflow:hidden" src="http://sjccantho.vn/libs/giavang.php?where=cantho"></iframe>
      </div>
    </div>
    <div class="tab-pane" id="angiang">
      <h3>An Giang</h3>
      <div class="cantho" id="content_angiang">
                            <iframe width="100%" scrolling="yes" height="250" frameborder="0" style="border:0px; overflow:hidden" src="http://sjccantho.vn/libs/giavang.php?where=angiang"></iframe>
      </div>
    </div>
  </div>
</div>

