<div class="section">
  <div id="posts" class="post_center">
    <h2 style="font-size: 12px;">Biểu đồ giá vàng 24h - live</h2>
    <img width="180" height="114" alt="24 hr gold chart" src="http://www.kitco.com/images/live/t24_au_en_usoz_home.gif?random=<?=date("YmdHi")?>">
  </div>
  <div id="posts" class="post_center">
    <h2 style="font-size: 16px;">BIỂU ĐỒ USD INDEX</h2>
    <img width="180" height="114" alt="24 hr gold chart" src="http://www.weblinks247.com/indexes/idx24_usd_en_2.gif?random=<?=date("YmdH")?>">
  </div>
</div>