<style>
   
</style>

<div class="box-header">
    GÍA VÀNG & NGOẠI TỆ THAM KHẢO
</div>
<div class="box-content row">
    <div class="span5 banggiangoaite_left">
                <div class="title-bang-gia">BẢNG GIÁ NGOẠI TỆ</div>

        <div>
        <h5 id="waiting">Hệ thống đang cập nhật giá vui lòng đợi giây lát ... ... ...</h5>
        <div>
<!--            <span style="font-weight: bold; color: #f00;">Chú ý: </span>Nếu bạn thấy hiển thị ký tự <strong>"NaN"</strong> vui lòng nhấn phím F5. Nếu sau nhiều lần nhấn phím F5 vẫn không có giá vui lòng liên hệ lại với chúng tôi. Xin cảm ơn.-->
        </div>
        <table style="width: 90%; margin-left: 10px;"  class="load">
            <tr>
                <td class="fonthead">Tên</td>
                <td class="fonthead">Mua</td>
                <td class="fonthead">Bán</td>
                <td class="fonthead hidden">C/L</td>        
            </tr>
            <tr>
                <td class="fontxanhla" id="tieude1">BP 999</td>
                <td id="M_FAN" class="fontred">0</td>
                <td id="B_FAN" class="fontred">0</td>                 
                <td  class="hidden" > </td>
            </tr>
            <tr>
                <td class="fontxanhla" id="tieude2">BK 9999</td>
                <td id="M_BK" class="fontred">0</td>
                <td id="B_BK" class="fontred">0</td>                 
                <td  class="hidden" > </td>
            </tr>
            <tr>
                <td class="fontxanhla" id="tieude3">950</td>
                <td id="M_95" class="fontred">0</td>
                <td id="B_95" class="fontred">0</td>                 
                <td class="hidden" > </td>
            </tr>  
            <tr>
                <td class="fontxanhla" id="tieude3">Si</td>
                <td id="M_SJC" class="fontred">0</td>
                <td id="B_SJC" class="fontred">0</td>                 
                <td class="hidden" > </td>
            </tr>  

            <tr>
                <td class="k18">USD (Mỹ)</td>
                <td id="M_US" class="k18" ></td>
                <td class="k18"> 100 </td>  
                <td class="k18 hidden"> </td>
            </tr>

            <tr>
                <td class="fonthead">AUD (Úc)</td>
                <td id="AUD" class="fontred"> </td>
                <td id="A2" class="fontred">100 </td>
                <td id="A5" class="fontred hidden"> </td>
            </tr>
            <tr>
                <td class="fonthead">CAD (Canada)</td>
                <td id="CAD" class="fontred"></td>
                <td id="C2" class="fontred">100</td>
                <td id="C5" class="fontred hidden"> </td>
            </tr>
            <tr>
                <td class="fonthead">CHF (Thụy Sỹ)</td>
                <td id="CHF" class="fontred"></td>
                <td id="CH2" class="fontred">100</td>
                <td  id="CH5 hidden" class="fontred hidden"> </td>
            </tr>
            <tr>
                <td class="fonthead">EUR (Euro)</td>
                <td id="EUR" class="fontred"></td>
                <td id="E2" class="fontred">100</td>  
                <td id="E5" class="fontred hidden"> </td>
            </tr>
            <tr>
                <td class="fonthead">GBP (Anh)</td>
                <td id="GBP" class="fontred"></td>
                <td id="G2" class="fontred">100</td>
                <td id="G5" class="fontred hidden"> </td>
            </tr>
            <tr>
                <td class="fonthead">JPY (Nhật)</td>
                <td id="JPY" class="fontred"></td>
                <td id="J2" class="fontred">10,000</td>
                <td id="J5" class="fontred hidden"> </td>
            </tr>
            <tr>
                <td class="fonthead">HKD (Hồng Kông)</td>
                <td id="HKD" class="fontred"></td>
                <td id="H2" class="fontred">100</td>
                <td id="H5" class="fontred hidden"> </td>
            </tr>
            <tr>
                <td class="fonthead">SGD (Singapore)</td>
                <td id="SGD" class="fontred"></td>
                <td id="SGD2" class="fontred">100</td>                
                <td id="SGD5" class="fontred hidden"> </td>                
            </tr>
            <tr>
                <td class="fonthead">THB (Thái Lan)</td>
                <td id="THB" class="fontred"></td>
                <td id="THB2" class="fontred">1,000</td>
                <td  id="THB5" class="fontred hidden"> </td>
            </tr>
            <tr>
                <td class="fonthead">CNY (Trung Quốc)</td>
                <td  id="CNY" class="fontred"></td>
                <td  id="CNY2" class="fontred">100</td>  
                <td id="CNY5" class="fontred hidden"> </td>
            </tr>
            <tr>
                <td class="fonthead">KRW (Hàn Quốc)</td>
                <td id="KRW" class="fontred"></td>
                <td id="K2" class="fontred">10,000</td>   
                <td id="K5" class="fontred hidden"> </td>
            </tr>
            <tr>
                <td class="fonthead">MYR (Malaysia)</td>
                <td id="MYR" class="fontred"></td>
                <td id="M2" class="fontred">100</td> 
                <td id="M5" class="fontred hidden"> </td>
            </tr>
            <tr>
                <td class="fonthead">TWD (Đài Loan)</td>
                <td id="TWD" class="fontred"></td>
                <td id="TW2" class="fontred">1,000</td>
                <td id="TW5" class="fontred hidden"> </td>
            </tr>
        </table> 
        </div>
    </div>
    <div class="banggiangoaite_right">
        <div class="ads_2">
            <br /><br />
            Banner Quảng Cáo
            <br />
            180x200
            <br/>
            Mr. Khánh - 0918.355.155
            <br/>
            5
        </div>

        <div class="ads_2">
            <br /><br />
            Banner Quảng Cáo
            <br />
            180x200
            <br/>
            Mr. Khánh - 0918.355.155
            <br/>
            6
        </div>
        <div class="ads_2">
            <br /><br />
            Banner Quảng Cáo
            <br />
            180x200
            <br/>
            Mr. Khánh - 0918.355.155
            <br/>
           7
        </div>
        
    </div>
    <div style="clear: both"></div>


</div>
<!--
 <div class="banggiangoaite_left">
        <div class="border1" style="text-align: center; font-family: Arial;">
            <h4 id="waiting">Hệ thống đang cập nhật giá vui lòng đợi giây lát ... ... ...</h4>
            <div>
                <span style="font-weight: bold; color: #f00;">Chú ý: </span>Nếu bạn thấy hiển thị ký tự <strong>"NaN"</strong> vui lòng nhấn phím F5. Nếu sau nhiều lần nhấn phím F5 vẫn không có giá vui lòng liên hệ lại với chúng tôi. Xin cảm ơn.
            </div>
            <table style="width: 90%; margin-left: 10px;"  class="load">
                <tr>
                    <td class="fonthead">Tên</td>
                    <td class="fonthead">Mua</td>
                    <td class="fonthead">Bán</td>
                    <td class="fonthead hidden">C/L</td>        
                </tr>
                <tr>
                    <td class="fontxanhla" id="tieude1">BP 999</td>
                    <td id="M_FAN" class="fontred">0</td>
                    <td id="B_FAN" class="fontred">0</td>                 
                    <td  class="hidden" > </td>
                </tr>
                <tr>
                    <td class="fontxanhla" id="tieude2">BK 9999</td>
                    <td id="M_BK" class="fontred">0</td>
                    <td id="B_BK" class="fontred">0</td>                 
                    <td  class="hidden" > </td>
                </tr>
                <tr>
                    <td class="fontxanhla" id="tieude3">950</td>
                    <td id="M_95" class="fontred">0</td>
                    <td id="B_95" class="fontred">0</td>                 
                    <td class="hidden" > </td>
                </tr>  
                <tr>
                    <td class="fontxanhla" id="tieude3">Si</td>
                    <td id="M_SJC" class="fontred">0</td>
                    <td id="B_SJC" class="fontred">0</td>                 
                    <td class="hidden" > </td>
                </tr>  

                <tr>
                    <td class="k18">USD (Mỹ)</td>
                    <td id="M_US" class="k18" ></td>
                    <td class="k18"> 100 </td>  
                    <td class="k18 hidden"> </td>
                </tr>

                <tr>
                    <td class="fonthead">AUD (Úc)</td>
                    <td id="AUD" class="fontred"> </td>
                    <td id="A2" class="fontred">100 </td>
                    <td id="A5" class="fontred hidden"> </td>
                </tr>
                <tr>
                    <td class="fonthead">CAD (Canada)</td>
                    <td id="CAD" class="fontred"></td>
                    <td id="C2" class="fontred">100</td>
                    <td id="C5" class="fontred hidden"> </td>
                </tr>
                <tr>
                    <td class="fonthead">CHF (Thụy Sỹ)</td>
                    <td id="CHF" class="fontred"></td>
                    <td id="CH2" class="fontred">100</td>
                    <td  id="CH5 hidden" class="fontred hidden"> </td>
                </tr>
                <tr>
                    <td class="fonthead">EUR (Euro)</td>
                    <td id="EUR" class="fontred"></td>
                    <td id="E2" class="fontred">100</td>  
                    <td id="E5" class="fontred hidden"> </td>
                </tr>
                <tr>
                    <td class="fonthead">GBP (Anh)</td>
                    <td id="GBP" class="fontred"></td>
                    <td id="G2" class="fontred">100</td>
                    <td id="G5" class="fontred hidden"> </td>
                </tr>
                <tr>
                    <td class="fonthead">JPY (Nhật)</td>
                    <td id="JPY" class="fontred"></td>
                    <td id="J2" class="fontred">10,000</td>
                    <td id="J5" class="fontred hidden"> </td>
                </tr>
                <tr>
                    <td class="fonthead">HKD (Hồng Kông)</td>
                    <td id="HKD" class="fontred"></td>
                    <td id="H2" class="fontred">100</td>
                    <td id="H5" class="fontred hidden"> </td>
                </tr>
                <tr>
                    <td class="fonthead">SGD (Singapore)</td>
                    <td id="SGD" class="fontred"></td>
                    <td id="SGD2" class="fontred">100</td>                
                    <td id="SGD5" class="fontred hidden"> </td>                
                </tr>
                <tr>
                    <td class="fonthead">THB (Thái Lan)</td>
                    <td id="THB" class="fontred"></td>
                    <td id="THB2" class="fontred">1,000</td>
                    <td  id="THB5" class="fontred hidden"> </td>
                </tr>
                <tr>
                    <td class="fonthead">CNY (Trung Quốc)</td>
                    <td  id="CNY" class="fontred"></td>
                    <td  id="CNY2" class="fontred">100</td>  
                    <td id="CNY5" class="fontred hidden"> </td>
                </tr>
                <tr>
                    <td class="fonthead">KRW (Hàn Quốc)</td>
                    <td id="KRW" class="fontred"></td>
                    <td id="K2" class="fontred">10,000</td>   
                    <td id="K5" class="fontred hidden"> </td>
                </tr>
                <tr>
                    <td class="fonthead">MYR (Malaysia)</td>
                    <td id="MYR" class="fontred"></td>
                    <td id="M2" class="fontred">100</td> 
                    <td id="M5" class="fontred hidden"> </td>
                </tr>
                <tr>
                    <td class="fonthead">TWD (Đài Loan)</td>
                    <td id="TWD" class="fontred"></td>
                    <td id="TW2" class="fontred">1,000</td>
                    <td id="TW5" class="fontred hidden"> </td>
                </tr>
            </table>
        </div>
    </div>-->