
<style>

   



</style>
<div class="box-header">
    Giá Thế Giới
</div>

<div class="box-content">       
    
<div class="button-row ">
        
            <div id="css_sell" class="sell down no-change">
                <span>bán</span>
                            
                <div class="corner">
                    <div class="bottom-corner bg_color"></div>
                </div>
                <div class="sell_value">
                    <div id="bid">0</div>
                    <span class="arrow"></span>
                </div>
            </div>
            <div class="middle_col">
                <div id="spread_val" class="spread">0</div>
            </div>
            <div id="css_buy" class="buy down no-change">
                <span>mua</span>
                            
                <div class="corner">
                    <div class="bottom-corner bg_color"></div>
                </div>
                <div class="buy_value">
                    <div id="ask">0</div>
                    <span class="arrow"></span>
                </div>
            </div>
       
    </div>
 
  
  


</div>
 