<style>
    
</style>

<div class="box-main-header">
        <h1 class="box-main-header-title">
            <span class="box-main-header-title-icon">GIÁ THẾ GIỚI</span>
            </h1>
    </div>
<div style="background-color: #FDE196; border-radius: 5px; padding: 10px;" class="box-main-content">
               
        <table class="gia-the-gioi" width="100%">
            <tr>
                <td width="30%" class="gia-the-gioi-title gia-the-gioi-title-ban">BÁN</td>
                <td id="spread_val"></td>
                <td width="30%" class="gia-the-gioi-title gia-the-gioi-title-mua">MUA</td>
            </tr>
           </table>  
            <table class="gia-the-gioi2" width="100%">
            <tr>
                <td width="42%" class="gia-the-gioi-gia">
                    <span id="icon-gia-ban" class="gia-the-gioi-gia-ban glyphicon glyphicon-arrow-up" aria-hidden="true"></span><span id="gia-ban">0</span>
                </td>
                <td></td>
                <td width="42%" class="gia-the-gioi-gia">
                    <span id="icon-gia-mua" class="gia-the-gioi-gia-mua gia-the-gioi-value glyphicon glyphicon-arrow-down pull-right" aria-hidden="true"></span><span id="gia-mua" class="pull-right">0</span>
                </td>
            </tr>
        </table>
        

    </div>
