<div class="box-main-header">
    <h1 class="box-main-header-title">
            <span class="box-main-header-title-icon">LỊCH CÔNG BỐ THÔNG TIN</span>
            </h1>
  
</div>
<div class="box-main-content">

      <iframe width="100%" scrolling="yes" height="800" frameborder="0" style="border:0px; overflow:hidden" src="http://www.fxstreet.com.vn/economic-calendar/?id=2fb7db07-4383-4bda-baea-4332c8c4c175"></iframe>

</div>

