
<div class="box-main-header">
        <h1 class="box-main-header-title">
            <span class="box-main-header-title-icon">GIÁ VÀNG TẠI GIAVANG.NET</span>
            </h1>
    </div>
    <div class="box-main-content">
              <iframe width="100%" scrolling="yes" height="500" frameborder="0" style="border:0px; overflow:hidden" src="http://vip.giavang.net/teline2/data/banggiavang1.php"></iframe>

    </div>