<div class="box-header">
  Giá vàng tại Giá vàng NET
</div>
<div class="box-content">
<!--  <ul class="nav nav-tabs" id="myTab_GiaVangNet">
    <li class="active"><a data-toggle="tab" href="#trang_1">Trang 1</a></li>
    <li><a data-toggle="tab" href="#trang_2">Trang 2</a></li>
    <li><a data-toggle="tab" href="#trang_3">Trang 3</a></li>
  </ul>

  <div class="tab-content">
    <div class="tab-pane active" id="trang_1">-->
      <iframe width="100%" scrolling="yes" height="355" frameborder="0" style="border:0px; overflow:hidden" src="http://vip.giavang.net/teline2/data/banggiavang1.php"></iframe>
<!--    </div>
    <div class="tab-pane" id="trang_2">
      <iframe width="100%" scrolling="yes" height="640" src="http://vip.giavang.net/data/aj2.php"></iframe>
    </div>
    <div class="tab-pane" id="trang_3">
      <iframe width="100%" scrolling="yes" height="640" frameborder="0" allowtransparency="true" src="http://vip.giavang.net/data/aj2a.php" border="0">
      </iframe>
    </div>
  </div>-->
</div>

