
<link href="<?php echo NHK_URL::getLinkPublic("plugin") ?>/animated_modal/css.css?t=125" media="screen" rel="stylesheet" type="text/css" />

<div style="display: none;"  class="box giavang-maiquyen">
      <?php //echo $this->render('index/giavangmaiquyen.phtml'); ?>
  </div>
   <div style="display: none;"  class="box giangoaite-maiquyen">
      <?php //echo $this->render('index/giavangmaiquyen.phtml'); ?>
  </div>
<div class="box">
    <?php echo $this->render('index/divGiaVangNgoaiTe.phtml'); ?>
</div>

<div class="box">
    <?php echo $this->render('index/divGiaTheGioi.phtml'); ?>
</div>

<div class="box giavangnet">
    <?php echo $this->render('index/giavangnet.phtml'); ?>
</div>
<div class="box giavangnet">
    <?php echo $this->render('index/fxstreet.phtml'); ?>
</div>

<div id="modal_login" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Thông Báo</h3>
  </div>
  <div class="modal-body">
    <?php if(isset($this->result) && $this->result){
	?>	
		<div class="error_alert alert alert-block alert-error fade in">			
			<?=$this->result;?>
		</div>
		
	<?php 
		}
	?>
                 <?php if(isset($this->errors)): ?>
  <div id="errorModal" class="alert alert-error">
    <h4>Lỗi Đăng Nhập</h4>
      <?php //print_r($this->error); ?>
    <ul>
        <?php foreach($this->errors as $k=>$v): ?>
      <li>
          <?= $k ?>
        <ul>
              <?php foreach($v as $item): ?>
          <li><?= $item ?></li>
                <?php endforeach; ?>
        </ul>
      </li>
      
        <?php endforeach; ?>
    </ul>
  </div>
  <?php endif; ?>
   <?php //echo $this -> render('common/_error_handle.phtml'); ?>
  </div>
    
    
  
</div>


<div style="display: none;">
  <div id="modal-content-demo" class="modal-content">
      <p>&nbsp;</p>
      <h1 id="modal-header"></h1>
    <div class="wrapper">
      
    </div>
  </div>
</div>
 <script src="<?php echo NHK_URL::getLinkPublic("js") ?>/default.js?t=001" type="text/javascript"></script>
 <script src="<?php echo NHK_URL::getLinkPublic("plugin") ?>/animated_modal/js.js" type="text/javascript"></script>

<script type="text/javascript">
    var url = '<?= NHK_URL::getLinkControllerDefault('index') ?>';
   



    $(document).ready(function () {

        init();
        auto_get_value();
                
        show_modal_login();
       
        

    });

    init = function () {
       
        displayGold();
        displayCurrence();
        displayNotification(); 
        getGiaTheGioi();
        
    };

    auto_get_value = function () {
        setInterval(displayGold, 300000);       
        setInterval(displayCurrence, 400000);        
              
        setInterval(getGiaTheGioi, 300000);
    };
    

</script>


