<link href="<?php echo NHK_URL::getLinkPublic("plugin") ?>/animated_modal/css.css?t=125" media="screen" rel="stylesheet" type="text/css" />
<!--
<div class="box-main">
    <div class="box-main-header">
        <h1 class="box-main-header-title">
            <span class="box-main-header-title-icon">GIÁ VÀNG & NGOẠI TỆ THAM KHẢO</span>
            </h1>
    </div>
    <div class="box-main-content">
        <div style="font-weight: bold; font-size: 18px; text-align: center; padding: 30px; color: #FFF;">
            Vui lòng <span style="color: #FDE196;">ĐĂNG NHẬP</span> để xem được giá.<br /><br />
            Liên hệ <span style="color: #FDE196;"> 0918.355.155 </span> để biết thêm chi tiết.
        </div>
    </div>
</div>-->
<div class="box-main">
    <?php echo $this->partial('index/divTinTucNoiBat.phtml',array('news'=>$this->news)); ?>
</div>
<div class="box-main">
    <?php echo $this->render('index/divGiaTheGioi.phtml'); ?>
</div>
<div class="box-main giavangnet">
    <?php echo $this->render('index/giavangnet.phtml'); ?>
</div>
<div class="box-main giavangnet">
    <?php echo $this->render('index/fxstreet.phtml'); ?>
</div>

<div class="modal fade" id="modal_login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Thông Báo</h4>
      </div>
      <div class="modal-body">
         <?php if (isset($this->result) && $this->result) {
            ?>	
            <div class="error_alert alert alert-block alert-error fade in">			
                <?= $this->result; ?>
            </div>

            <?php
        }
        ?>
        <?php if (isset($this->errors)): ?>
            <div id="errorModal" class="alert alert-error">
                <h4>Lỗi Đăng Nhập</h4>
                <?php //print_r($this->error); ?>
                <ul>
                    <?php foreach ($this->errors as $k => $v): ?>
                        <li>
                            <?= $k ?>
                            <ul>
                                <?php foreach ($v as $item): ?>
                                    <li><?= $item ?></li>
                                <?php endforeach; ?>
                            </ul>
                        </li>

                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>





<div style="display: none;">
  <div id="modal-content-demo" class="modal-content">
      <p>&nbsp;</p>
      <h1 id="modal-header"></h1>
    <div class="wrapper">
      
    </div>
  </div>
</div>
<script src="<?php echo NHK_URL::getLinkPublic("js") ?>/default.js?t=001" type="text/javascript"></script>
<script src="<?php echo NHK_URL::getLinkPublic("plugin") ?>/animated_modal/js.js" type="text/javascript"></script>



<script type="text/javascript">
    var url = '<?= NHK_URL::getLinkControllerDefault('index') ?>';

    $(document).ready(function () {

        init();
        auto_get_value();
        show_modal_login();
       

    });

    init = function () {       
        getGiaTheGioi();
        displayNotification();
    };

    auto_get_value = function () {        
        setInterval(getGiaTheGioi, 300000);

    };




</script>


