<div id="footer" class="navbar  navbar-fixed-bottom">
  <div class="navbar-inner">
      <div class="container-fluid">
          <p align="center" style="padding-top: 10px;">
              ©<a href="http://www.maxsupport.co.jp/" rel="http://www.maxsupport.co.jp/"> Max Support Co., Ltd</a>.  Powered by <a href="http://jv-it.com.vn" rel="http://jv-it.com.vn" >JV-IT., JSC</a>
          </p>
      </div>
      
  </div>
</div>
