<!DOCTYPE html>
<?php
echo $this->doctype();
$properties = Zend_Registry::get('properties');
?>
<html lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <title><?php echo NHK_Properties::get("title_page", 'public', $properties); ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <?php echo $this->headMeta(); ?>

    <?php echo $this->headLink(); ?>


    <link href="<?php echo NHK_URL::getLinkPublic("css") ?>/bootstrap.css" media="screen" rel="stylesheet" type="text/css" />
    <link href="<?php echo NHK_URL::getLinkPublic("css") ?>/bootstrap-responsive.min.css" media="screen" rel="stylesheet" type="text/css" />
    <link href="<?php echo NHK_URL::getLinkPublic("css") ?>/style.css" media="screen" rel="stylesheet" type="text/css" />

    <!-- Le styles -->
    <script src="<?php echo NHK_URL::getLinkPublic("js") ?>/jquery-1.8.2.min.js" type="text/javascript"></script>



  </head>

  <body>

    <?php echo $this->render('/menu.phtml'); ?>

    <div class="container-fluid">

      <div class="row-fluid">
        <?php echo $this->layout()->content; ?>                    
      </div><!--/row-->



      <footer>
        <?php echo $this->render('/footer.phtml'); ?>
      </footer>

    </div><!--/.fluid-container-->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <script src="<?php echo NHK_URL::getLinkPublic("js") ?>/bootstrap.min.js" type="text/javascript"></script>

    <script type="text/javascript">
         $(document).ready(function() {
             $('a.dropdown-toggle, .dropdown-menu a').on('touchstart', function(e) {
  e.stopPropagation();
});
         });

    </script>
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-65648669-1', 'auto');
  ga('send', 'pageview');

</script>
    
  </body>
</html>

