<!DOCTYPE html>
<?php
echo $this->doctype();
$properties = Zend_Registry::get('properties');
?>
<html lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <title><?php echo NHK_Properties::get("title_page", 'public', $properties); ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <?php echo $this->headMeta(); ?>

    <?php echo $this->headLink(); ?>


    <link href="<?php echo NHK_URL::getLinkPublic("css") ?>/jquery.mobile-1.4.5.min.css" media="screen" rel="stylesheet" type="text/css" />
    <link href="<?php echo NHK_URL::getLinkPublic("css") ?>/style_mobile.css" media="screen" rel="stylesheet" type="text/css" />

    <!-- styles -->
    <script src="<?php echo NHK_URL::getLinkPublic("js") ?>/jquery-1.8.2.min.js" type="text/javascript"></script>



  </head>

  <body>

    <?php //echo $this->render('/menu.phtml'); ?>

      <div data-role="page">
 
        <div data-role="header">
            <h1>My Title</h1>
        </div><!-- /header -->
 
        <div data-role="content">
             <?php echo $this->layout()->content; ?>    
        </div><!-- /content -->
 
        <div data-role="footer">
            <h4>My Footer</h4>
        </div><!-- /footer -->
 
    </div><!-- /page -->
   
                       
     

    <script src="<?php echo NHK_URL::getLinkPublic("js") ?>/jquery.mobile-1.4.5.min.js" type="text/javascript"></script>

  </body>
</html>

