<style>

</style>
<div class="box">
    <div class="box-header">THÔNG TIN LIÊN HỆ</div>
    <div class="box-content">
        <dl>
            <dt>Địa chỉ: 226 QUANG TRUNG K5, P5, TP CÀ MAU</dt>
            <dd>Điện thoại & Fax: 07803.811.911</dd>
            <dd>Di Động : 0918.355.155</dd>
            <dd>Mail: hoikimhoancamau@gmail.com</dd>
            <dd>Website: www.hoikimhoancamau.com</dd>
        </dl>



        <h2> TIỆM VÀNG PHƯỚC THẠNH</h2>
        <ul> 
            <li> Địa chỉ: 08 Lý Văn Lâm, P1, TP. Cà Mau</li> 
            <li> Tel: 0780.3811911 - 0918.355.155</li> 
            <li> Email: phuocthanh.net.vn@gmail.com</li> 
            <li> Web&nbsp; : www.phuocthanh.net.vn - www.phuocthanhthinh.com.vn&nbsp;&nbsp;</li> 

        </ul>
        <br  />
        <div class="border-img "> <iframe frameborder="0" height="250" src="https://www.google.com/maps/embed?pb=!1m5!3m3!1m2!1s0x31a1499dca153fbf%3A0x54e158293da57af9!2zOCBMw70gVsSDbiBMw6JtLCB0cC4gQ8OgIE1hdSwgQ8OgIE1hdSwgVmnhu4d0IE5hbQ!5e0!3m2!1svi!2s!4v1389606843195" style="border:0" width="100%"></iframe></div>

    </div>

</div>



