<style>
  .ads{
    position: fixed;
    top: 120px;    
    padding: 2px;
  }
  .ads ul{
    margin: 0px;
  }
  .ads ul li{
    list-style: none;
    margin-bottom: 4px;
  }
  .ads ul li a{
    text-align: center;
  }
  .ads ul li img{
    border: 1px solid #ddd;
    border-radius:3px;
    padding: 2px;
  }
  .ads ul li .title{
    border: 1px solid #ddd;
    border-radius:3px;
    background-color: #ddd;
    font-size: 12px;
  }
  .ads.ads-pull-left{
    left: 0px;
  }
  .ads.ads-pull-right{
    right: 0px;
  }
  
  </style>
  <div class="ads ads-pull-left">
    <ul>
      <li>
        <a href="http://localhost/vjg/news/detail/id/1" title="Lễ trao tặng bằng khen 'Hàng Thật - Chính Hảng - Thương Hiệu Độc Quyền'">
          <div>
            <div>
              <img width="110" src="<?= NHK_URL::getLinkPublic('img') ?>/thumb/thumb_mai_quyen_75_hang_that_shinh_hang.jpg" alt="thumb_mai_quyen_75_hang_that_shinh_hang" />
            </div>
              <div class="title" style="width: 110px;">
              Lễ trao tặng bằng khen "Hàng Thật - Chính Hảng - Thương Hiệu Độc Quyền"
            </div>  
          </div>
        </a>
      </li>
      <!--
      <li>
        <a href="javascrip:" title="">
          <div>
            <div>
              <img width="110" src="<?= NHK_URL::getLinkPublic('img') ?>/ads/hdbank.png" alt="HDBank" />
            </div>
            <div class="title">
              HD Bank
            </div>  
          </div>
        </a>
      </li>
      <li>
        <a href="javascrip:" title="">
          <div>
            <div>
              <img width="110" src="<?= NHK_URL::getLinkPublic('img') ?>/ads/mitsubishi.png" alt="mitsubishi" />
            </div>
            <div class="title">
              Mitsubishi
            </div>  
          </div>
        </a>
      </li>   -->         
    </ul>
  </div>
  
  <div class="ads ads-pull-right">
    <ul>
        <!--
      <li>
        <a href="javascrip:" title="">
          <div>
            <div>
              <img width="110" src="<?= NHK_URL::getLinkPublic('img') ?>/ads/seabank.png" alt="seabank" />
            </div>
            <div class="title">
              Sea Bank
            </div>  
          </div>
        </a>
      </li>
      <li>
        <a href="javascrip:" title="">
          <div>
            <div>
              <img width="110" src="<?= NHK_URL::getLinkPublic('img') ?>/ads/slide_1.png" alt="phong_cach_moi" />
            </div>
            <div class="title">
              Phong cách mới
            </div>  
          </div>
        </a>
      </li>
      <li>
        <a href="javascrip:" title="">
          <div>
            <div>
              <img width="110" src="<?= NHK_URL::getLinkPublic('img') ?>/ads/vpbank.png" alt="vpbank" />
            </div>
            <div class="title">
              VP Bank
            </div>  
          </div>
        </a>
      </li>       
        -->
    </ul>
  </div>