<div class="ads-main">
    <img src="<?php echo NHK_URL::getLinkPublic("img") ?>/ads/thunam.gif" />
</div>
<div class="ads-main">
    <a target="_about" href="http://giavang9999.vn" title="Tiệm Vàng Phương Nam"> 
    <img src="<?php echo NHK_URL::getLinkPublic("img") ?>/ads/banner-4.gif" />
     </a>
</div>
<div class="ads-main">
    <a target="_about" href="http://tiemvangthanhtrung.vn" title="Tiệm Vàng Thành Trung"> 
        <img src="<?php echo NHK_URL::getLinkPublic("img") ?>/ads/banner_thanh_trung.gif" />
    </a>
</div>
