<style>
  .footer{
    margin: auto;
  
  }
  .footer-ads{
    padding: 2px;
    text-align: center;
      border-top: 1px double #ddd;
    border-bottom: 1px double #ddd;
    padding-top: 5px;
    padding-bottom: 5px;
  }
  .footer-ads ul{
    margin: 0px;
    display: table;
    margin: auto;
  }
  .footer-ads ul li{
    list-style: none;
    padding-right: 5px;
    display: table-cell;
  }
  .footer-ads ul li a{
    text-align: center;
  }
  .footer-ads ul li img{
    border: 1px solid #ddd;
    border-radius:3px;
    padding: 2px;
  }
  .footer-ads ul li .title{
    border: 1px solid #ddd;
    border-radius:3px;
    background-color: #ddd;
  }
  .footer-ads.footer-ads-pull-left{
    left: 0px;
  }
  .footer-ads.footer-ads-pull-right{
    right: 0px;
  }
  
  </style>
  <ul>
      <li>
        <a href="javascrip:" title="">
          <div>
            <div>
              <img src="<?= NHK_URL::getLinkPublic('img') ?>/ads/DongAbank.jpg" alt="DongAbank" />
            </div>
            <div class="title">
              Đông Á Bank
            </div>  
          </div>
        </a>
      </li>
      <li>
        <a href="javascrip:" title="">
          <div>
            <div>
              <img src="<?= NHK_URL::getLinkPublic('img') ?>/ads/hdbank.png" alt="HDBank" />
            </div>
            <div class="title">
              HD Bank
            </div>  
          </div>
        </a>
      </li>
      <li>
        <a href="javascrip:" title="">
          <div>
            <div>
              <img src="<?= NHK_URL::getLinkPublic('img') ?>/ads/mitsubishi.png" alt="mitsubishi" />
            </div>
            <div class="title">
              Mitsubishi
            </div>  
          </div>
        </a>
      </li>            
    </ul>