<div class="footer">
    <div class="footer_left">
        <dl>
            <dt>Địa chỉ: 226 QUANG TRUNG K5, P5, TP CÀ MAU</dt>
            <dd>Điện thoại & Fax: 07803.811.911</dd>
            <dd>Di Động : 0918.355.155</dd>
            <dd>Mail: hoikimhoancamau@gmail.com</dd>
            <dd>Website: www.hoikimhoancamau.com</dd>
        </dl>
    </div>
    
    <div class="footer_right">
        <div class="block-stat">
            <ul>
                <li class="today">Hôm nay: <strong>1288</strong></li>
                                <li class="month">Tháng hiện tại: <strong>36357</strong></li>
                                <li class="statistics">Tổng lượt truy cập: <strong>1241841</strong></li>
            </ul>
        </div>
    </div>
    
    <div class="footer_right">
        <div class="block-stat">
                            <ul>
                                <li class="online">Đang truy cập: <strong>107</strong></li>
                                <li class="guest">Khách viếng thăm: <strong>94</strong></li>
                                <li class="user">Thành viên online: <strong>12</strong></li>                      
                                
                            </ul>
                        </div>
    </div>
    <div style="clear: both;"></div>
</div>




<p style="float: right;">&copy; HỘI MỸ NGHỆ KIM HOÀN TỈNH CÀ MAU</p>