<div style="border-top: 3px double #ED0C18">
    &nbsp;
</div>
<div class="footer container">
    <div class="row">
        <div class="col-xs-12 col-md-7 footer_left">
        <dl>
            <dt><span class="glyphicon glyphicon-map-marker"></span>&nbsp;&nbsp;Địa chỉ: 08 Lý Văn Lâm, khóm 4, P1, TP CÀ MAU</dt>
            <dt><span class="glyphicon glyphicon-phone-alt"></span>&nbsp;&nbsp;Điện thoại: 0290.3.811.911</dt>
            <dt><span class="glyphicon glyphicon-phone"></span>&nbsp;&nbsp;Di Động : 0918.355.155</dt>
            <dt><span class="glyphicon glyphicon-envelope"></span>&nbsp;&nbsp;Mail: phuocthanh.net.vn@gmail.com</dt>
            <dt><span class="glyphicon glyphicon-globe"></span>&nbsp;&nbsp;Website: www.phuocthanhthinh.com.vn</dt>
        </dl>
         <img style="margin-right: 20px;margin-top: 5px;" height="40" src="<?php echo NHK_URL::getLinkPublic("images") ?>/logo_pt.png" />
        <p>&copy; DOANH NGHIỆP TƯ NHÂN VÀNG PHƯỚC THẠNH</p>
    </div>

    <div class="col-xs-12 col-md-5 footer_right">
        <div class="block-stat">
            <ul>
                <li class="today">Hôm nay: <strong>1288</strong></li>
                <li class="month">Tháng hiện tại: <strong>36357</strong></li>
                <li class="statistics">Tổng lượt truy cập: <strong>1241841</strong></li>
                <li class="online">Đang truy cập: <strong>107</strong></li>
                <li class="guest">Khách viếng thăm: <strong>94</strong></li>
                <li class="user">Thành viên online: <strong>12</strong></li>
            </ul>
        </div>
        
    </div>
    </div>
    

    
    
    
</div>




