
<div class="row">
    <div class="col-xs-12 col-md-5">
        <img class="header-logo" src="<?php echo NHK_URL::getLinkPublic("images") ?>/logo2.png" />
    </div>
    <div class="col-xs-12 col-md-7">
        
        <div class="pull-right">
            <img class="header-logo" width="380" src="<?php echo NHK_URL::getLinkPublic("images") ?>/canhmai.png" />
        </div>
        <div class="clearfix"></div>
        <div style="font-size: 24px;font-weight: bold; text-align: right;color: #FAB905">
            HOTLINE : 0918.355.155
        </div>
    </div>
</div>