<div class="box">
    <div class="box-header">
        Thông tin đăng nhập
    </div>
    <div class="box-content">
        <?php if (User::is_login()) { ?>

            <p style="margin-left: 10px;" class="navbar-text pull-right">
                <a href="<?php echo NHK_URL::getLinkControllerDefault('index') . '/logout/' ?>" class="navbar-link">Đăng xuất</a>
            </p>
            <p style="margin-left: 10px;" class="navbar-text pull-right">
                |
            </p>
            <p class="navbar-text pull-right">    
                <?php $date_exp = new DateTime(NHK_Auth::getUser()->time_expired); ?>
                <a target="_blank" href="<?= NHK_URL::getLinkControllerDefault('index') ?>/info/id/<?php echo NHK_Auth::getUser()->id; ?>" class="navbar-link"><?php echo NHK_Auth::getUser()->fullname; ?></a> . Hết hạn: <?= $date_exp->format("d-m-Y") ?> 
            </p>    
        <?php } else { ?>
            <form action="<?php echo NHK_URL::getLink("root") ?>/index/login" method="post"  class="navbar-form pull-right">

               
                <label for="inputEmail" class="sr-only">Email address</label>
                <input type="email" id="inputEmail" class="form-control" name="username" placeholder="Tài Khoản" required autofocus>
                
                <label for="inputPassword" class="sr-only">Password</label>
                <input style="margin-top: 5px;" type="password" id="inputPassword" class="form-control" name="password" placeholder="Mật Khẩu" required>
              
                <button style="margin-top: 5px;" class="btn btn-lg btn-danger" type="submit">Đăng Nhập</button>

              
        
            </form>
        <?php } ?>
    </div>
</div>