
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="Phuoc Thanh Thinh, Ca Mau">
    <meta name="author" content="Ngô Hồng Khánh, nhkhanh294@gmail.com">
    <link rel="icon" href="../../favicon.ico">

    <?php echo $this->headTitle(); ?>

    <!-- Bootstrap core CSS -->
    <link href="<?php echo NHK_URL::getLinkPublic("bootstrap3") ?>/css/bootstrap.css" rel="stylesheet">
    <link href="<?php echo NHK_URL::getLinkPublic("css") ?>/default_style.css?t=125" media="screen" rel="stylesheet" type="text/css" />
     <script src="<?php echo NHK_URL::getLinkPublic("js") ?>/jquery-3.2.1.min.js" type="text/javascript"></script>
    <script src="<?php echo NHK_URL::getLinkPublic("bootstrap3") ?>/js/bootstrap.min.js" type="text/javascript"></script>
  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <?php echo $this->render('/navigation.phtml'); ?>
    </nav>

    <div class="container">

       
      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
         <?php echo $this->render('/header.phtml'); ?>
      </div>
      <div class="row">
          <div class="col-xs-12 col-md-3">
              <?php echo $this->render('/left.phtml'); ?>
          </div>
          <div class="col-xs-12 col-md-9">
              <?php echo $this->layout()->content; ?> 
          </div>
      </div>
 <footer>
                <?php echo $this->render('/footer.phtml'); ?>
            </footer>
    </div> <!-- /container -->

<script type="text/javascript">
            var url_main = '<?= NHK_URL::getLinkControllerDefault('index') ?>';




            $(document).ready(function () {

                init_main();
                auto_call_func();


            });

            init_main = function () {
                checkOnline();
            };
            auto_call_func = function () {
                setInterval(checkOnline, 880000);
            };

            checkOnline = function () {
                $.get(url_main + '/check-online', {}, function (res) {
                    var data = JSON.parse(res);
                    $(".block-stat .statistics strong").html(data['statistics']);
                    $(".block-stat .today strong").html(data['today']);
                    $(".block-stat .month strong").html(data['month']);
                    $(".block-stat .online strong").html(data['online']);
                    $(".block-stat .guest strong").html(data['online'] - data['useronline']);
                    $(".block-stat .user strong").html(data['useronline']);

                });
            };
            
             

        </script>
  
    
  </body>
</html>
