
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle(); ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Hội Kim Hoàn Cà Mau">
        <meta name="author" content="nhkhanh294@gmail.com">

        <!-- Le styles -->

        <link href="<?php echo NHK_URL::getLinkPublic("css") ?>/bootstrap.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?php echo NHK_URL::getLinkPublic("css") ?>/bootstrap-responsive.css?t=125" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?php echo NHK_URL::getLinkPublic("css") ?>/default_style.css?t=125" media="screen" rel="stylesheet" type="text/css" />


        <style type="text/css">
            body{
                /*                background-image: url("./public/img/bg5.jpg");*/
                background-image: url(<?php echo NHK_URL::getLinkPublic("img") . "/bg5.jpg"; ?>);
                /*                    background-color: #C80101;*/
                /*background-repeat: no-repeat;*/

            }
           
           
           


            .block-stat ul li.online {

                background: url(<?php echo NHK_URL::getLinkPublic("img") . "/online/online.png"; ?>) 0 50% no-repeat;
            }
            .block-stat ul li.guest {
                background: url(<?php echo NHK_URL::getLinkPublic("img") . "/online/guest.png"; ?>) 0 50% no-repeat;
            }
            .block-stat ul li.user {
                background: url(<?php echo NHK_URL::getLinkPublic("img") . "/online/user.png"; ?>) 0 50% no-repeat;
            }
            .block-stat ul li.today {
                background: url(<?php echo NHK_URL::getLinkPublic("img") . "/online/time.png"; ?>) 0 50% no-repeat;
            }
            .block-stat ul li.month {
                background: url(<?php echo NHK_URL::getLinkPublic("img") . "/online/month.png"; ?>) 0 50% no-repeat;
            }
            .block-stat ul li.statistics {
                background: url(<?php echo NHK_URL::getLinkPublic("img") . "/online/statistics.png"; ?>) 0 50% no-repeat;
            }



        </style>




        <!-- Fav and touch icons -->
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
        <link rel="shortcut icon" href="../assets/ico/favicon.png">

        <script src="<?php echo NHK_URL::getLinkPublic("js") ?>/jquery-1.8.2.min.js" type="text/javascript"></script>
        <script src="<?php echo NHK_URL::getLinkPublic("js") ?>/bootstrap.min.js" type="text/javascript"></script>
    </head>

    <body>

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="bg_nav">
                <div class="container">
                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>          
                    <a style="float:left;padding-right: 10px;" href="<?= NHK_URL::getLinkControllerDefault('index') ?>" ><img style="width:38px;" src="<?php echo NHK_URL::getLinkPublic("img") ?>/logo.png" /></a>
                    <!--<a class="brand" href="#">HỘI KIM HOÀN CÀ MAU</a>-->
                    <div class="nav-collapse collapse">
                        <?php echo $this->render('/navigation.phtml'); ?>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>

        <div class="container">

            <!-- Main hero unit for a primary marketing message or call to action -->
            <div class="hero-unit">
                <?php echo $this->render('/header.phtml'); ?>
            </div>

            <!-- Example row of columns -->
            <div class="row">
                <div class="span2 ads">
                    <?php echo $this->render('/ads_left.phtml'); ?>

                   
                </div>
                <div class="span8">
                    <?php echo $this->layout()->content; ?> 
                </div>

                <div class="span2 ads">
                    <?php echo $this->render('/ads_right.phtml'); ?>

                </div>
            </div>



            <footer>
                <?php echo $this->render('/footer.phtml'); ?>
            </footer>


        </div> <!-- /container -->

        <!-- Le javascript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        
               

        <script type="text/javascript">
            var url_main = '<?= NHK_URL::getLinkControllerDefault('index') ?>';




            $(document).ready(function () {

                init_main();
                auto_call_func();


            });

            init_main = function () {
                checkOnline();
            };
            auto_call_func = function () {
                setInterval(checkOnline, 880000);
            };

            checkOnline = function () {
                $.get(url_main + '/check-online', {}, function (res) {
                    var data = JSON.parse(res);
                    $(".block-stat .statistics strong").html(data['statistics']);
                    $(".block-stat .today strong").html(data['today']);
                    $(".block-stat .month strong").html(data['month']);
                    $(".block-stat .online strong").html(data['online']);
                    $(".block-stat .guest strong").html(data['online'] - data['useronline']);
                    $(".block-stat .user strong").html(data['useronline']);

                });
            };
            
              (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){

		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),

		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)

		  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');



		  ga('create', 'UA-96102135-1', 'auto');

		  ga('send', 'pageview');

        </script>

    </body>
</html>
