<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>HỘI KIM HOÀN CÀ MAU</title>
    <?php echo $this->headTitle(); ?>
    <link href="<?php echo NHK_URL::getLinkPublic("css") ?>/bootstrap.css" media="screen" rel="stylesheet" type="text/css" />
    <link href="<?php echo NHK_URL::getLinkPublic("css") ?>/bootstrap-responsive.css" media="screen" rel="stylesheet" type="text/css" />
    <link href="<?php echo NHK_URL::getLinkPublic("css") ?>/default_style.css" media="screen" rel="stylesheet" type="text/css" />
    <script src="<?php echo NHK_URL::getLinkPublic("js") ?>/jquery-1.8.2.min.js" type="text/javascript"></script>

    
    <script type="text/javascript">
      $(document).ready(function(){
          func_display_ads();
          $(window).resize(function(){
            func_display_ads();
          });
      });
      func_display_ads = function(){
        var w = $(window).width();
        if(w < 1240){
          $(".ads").hide();
        }else{
          $(".ads").show();
        }
          
      };
    </script>
  </head>
  <body>
    <div class="container">

      <div class="masthead" style="position: fixed; top: 0px; background-color: #fff; width: 1000px;">
        <?php echo $this->render('/header.phtml'); ?>
        <div class="navbar">
          <?php echo $this->render('/navigation.phtml'); ?>
        </div><!-- /.navbar -->
      </div>

      <div style="margin-top: 102px" class="row content">                  
        <div class="span2">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
        <div class="span8">
          <?php echo $this->layout()->content; ?> 
       </div>
        <div class="span2">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
      

      </div>
      
      
     
      
      
      
      
      <div class="footer">
        <div class="footer-ads">
          <?php //echo $this->render('/ads_footer.phtml'); ?>
        </div>
        <?php echo $this->render('/footer.phtml'); ?>
      </div>

    </div> <!-- /container -->
    <?php echo $this->render('/ads.phtml'); ?>
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-65648669-1', 'auto');
  ga('send', 'pageview');

</script>
    
  </body>
</html>