<div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
            <img style="margin-right: 20px;margin-top: 5px;" height="40" src="<?php echo NHK_URL::getLinkPublic("images") ?>/logo_pt.png" />
          
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li <?php if ($this->menu == 'home') echo 'class="active"'; ?>><a href="<?= NHK_URL::getLinkControllerDefault('index') ?>">Trang Chủ</a></li>
            <li <?php if ($this->menu == 'news') echo 'class="active"'; ?>><a href="<?= NHK_URL::getLinkControllerDefault('news') ?>">Tin Tức</a></li>
          </ul>
      
        </div><!--/.nav-collapse -->
      </div>



